[package]
name = "hex-buffer-serde"
version = "0.1.0"
authors = ["Alex Ostrovski <ostrovski.alex@gmail.com>"]

[dependencies]
serde = "1.0"
hex = "0.3.2"
failure = "0.1.3"
failure_derive = "0.1.3"

[dev-dependencies]
serde_derive = "1.0"
serde_json = "1.0"
bincode = "1.0"
rand = "0.5.5"
ed25519-dalek = { version = "=1.0.0-pre.0", features = ["serde", "sha2"] }
